[
  './node_modules/.bin',
  './node_modules/@types',
  './node_modules/ansi-colors',
  './node_modules/ansi-regex',
  './node_modules/ansi-styles',
  './node_modules/anymatch',
  './node_modules/argparse',
  './node_modules/array.prototype.map',
  './node_modules/assertion-error',
  './node_modules/balanced-match',
  './node_modules/binary-extensions',
  './node_modules/brace-expansion',
  './node_modules/braces',
  './node_modules/browser-stdout',
  './node_modules/camelcase',
  './node_modules/chai',
  './node_modules/chalk',
  './node_modules/check-error',
  './node_modules/chokidar',
  './node_modules/cliui',
  './node_modules/color-convert',
  './node_modules/color-name',
  './node_modules/concat-map',
  './node_modules/daggy',
  './node_modules/debug',
  './node_modules/decamelize',
  './node_modules/deep-eql',
  './node_modules/define-properties',
  './node_modules/diff',
  './node_modules/emoji-regex',
  './node_modules/es-abstract',
  './node_modules/es-array-method-boxes-properly',
  './node_modules/es-get-iterator',
  './node_modules/es-to-primitive',
  './node_modules/escape-string-regexp',
  './node_modules/esprima',
  './node_modules/fantasy-combinators',
  './node_modules/fantasy-land',
  './node_modules/fantasy-laws',
  './node_modules/fill-range',
  './node_modules/find-up',
  './node_modules/flat',
  './node_modules/fs.realpath',
  './node_modules/fsevents',
  './node_modules/function-bind',
  './node_modules/get-caller-file',
  './node_modules/get-func-name',
  './node_modules/glob',
  './node_modules/glob-parent',
  './node_modules/growl',
  './node_modules/has',
  './node_modules/has-flag',
  './node_modules/has-symbols',
  './node_modules/he',
  './node_modules/inflight',
  './node_modules/inherits',
  './node_modules/is-arguments',
  './node_modules/is-binary-path',
  './node_modules/is-buffer',
  './node_modules/is-callable',
  './node_modules/is-date-object',
  './node_modules/is-extglob',
  './node_modules/is-fullwidth-code-point',
  './node_modules/is-glob',
  './node_modules/is-map',
  './node_modules/is-number',
  './node_modules/is-plain-obj',
  './node_modules/is-regex',
  './node_modules/is-set',
  './node_modules/is-string',
  './node_modules/is-symbol',
  './node_modules/isarray',
  './node_modules/isexe',
  './node_modules/iterate-iterator',
  './node_modules/iterate-value',
  './node_modules/js-yaml',
  './node_modules/jsverify',
  './node_modules/lazy-seq',
  './node_modules/locate-path',
  './node_modules/log-symbols',
  './node_modules/minimatch',
  './node_modules/mocha',
  './node_modules/ms',
  './node_modules/normalize-path',
  './node_modules/object-inspect',
  './node_modules/object-keys',
  './node_modules/object.assign',
  './node_modules/once',
  './node_modules/p-limit',
  './node_modules/p-locate',
  './node_modules/p-try',
  './node_modules/path-exists',
  './node_modules/path-is-absolute',
  './node_modules/pathval',
  './node_modules/picomatch',
  './node_modules/promise.allsettled',
  './node_modules/ramda',
  './node_modules/randombytes',
  './node_modules/rc4',
  './node_modules/readdirp',
  ... 34 more items
] ./node_modules 0000
[
  './node_modules/cliui/node_modules/ansi-regex',
  './node_modules/cliui/node_modules/string-width',
  './node_modules/cliui/node_modules/strip-ansi'
] ./node_modules/cliui/node_modules 0000
[
  './node_modules/fantasy-laws/node_modules/daggy',
  './node_modules/fantasy-laws/node_modules/fantasy-land',
  './node_modules/fantasy-laws/node_modules/sanctuary-show',
  './node_modules/fantasy-laws/node_modules/sanctuary-type-classes'
] ./node_modules/fantasy-laws/node_modules 0000
[
  './node_modules/sanctuary/node_modules/sanctuary-type-classes',
  './node_modules/sanctuary/node_modules/sanctuary-type-identifiers'
] ./node_modules/sanctuary/node_modules 0000
[
  './node_modules/sanctuary-def/node_modules/sanctuary-type-classes',
  './node_modules/sanctuary-def/node_modules/sanctuary-type-identifiers'
] ./node_modules/sanctuary-def/node_modules 0000
[
  './node_modules/sanctuary-either/node_modules/sanctuary-type-classes',
  './node_modules/sanctuary-either/node_modules/sanctuary-type-identifiers'
] ./node_modules/sanctuary-either/node_modules 0000
[
  './node_modules/sanctuary-maybe/node_modules/sanctuary-type-classes',
  './node_modules/sanctuary-maybe/node_modules/sanctuary-type-identifiers'
] ./node_modules/sanctuary-maybe/node_modules 0000
[
  './node_modules/sanctuary-pair/node_modules/sanctuary-type-classes',
  './node_modules/sanctuary-pair/node_modules/sanctuary-type-identifiers'
] ./node_modules/sanctuary-pair/node_modules 0000
[
  './node_modules/wrap-ansi/node_modules/ansi-regex',
  './node_modules/wrap-ansi/node_modules/ansi-styles',
  './node_modules/wrap-ansi/node_modules/color-convert',
  './node_modules/wrap-ansi/node_modules/color-name',
  './node_modules/wrap-ansi/node_modules/string-width',
  './node_modules/wrap-ansi/node_modules/strip-ansi'
] ./node_modules/wrap-ansi/node_modules 0000
[
  './node_modules/yargs/node_modules/ansi-regex',
  './node_modules/yargs/node_modules/find-up',
  './node_modules/yargs/node_modules/locate-path',
  './node_modules/yargs/node_modules/p-limit',
  './node_modules/yargs/node_modules/p-locate',
  './node_modules/yargs/node_modules/path-exists',
  './node_modules/yargs/node_modules/string-width',
  './node_modules/yargs/node_modules/strip-ansi'
] ./node_modules/yargs/node_modules 0000
[
  './node_modules/yargs-unparser/node_modules/ansi-regex',
  './node_modules/yargs-unparser/node_modules/find-up',
  './node_modules/yargs-unparser/node_modules/locate-path',
  './node_modules/yargs-unparser/node_modules/p-limit',
  './node_modules/yargs-unparser/node_modules/p-locate',
  './node_modules/yargs-unparser/node_modules/path-exists',
  './node_modules/yargs-unparser/node_modules/string-width',
  './node_modules/yargs-unparser/node_modules/strip-ansi',
  './node_modules/yargs-unparser/node_modules/yargs',
  './node_modules/yargs-unparser/node_modules/yargs-parser'
] ./node_modules/yargs-unparser/node_modules 0000
. {"node":".","forest":[{"node":"./node_modules/.bin","forest":[]},{"node":"./node_modules/@types","forest":[]},{"node":"./node_modules/ansi-colors","forest":[]},{"node":"./node_modules/ansi-regex","forest":[]},{"node":"./node_modules/ansi-styles","forest":[]},{"node":"./node_modules/anymatch","forest":[]},{"node":"./node_modules/argparse","forest":[]},{"node":"./node_modules/array.prototype.map","forest":[]},{"node":"./node_modules/assertion-error","forest":[]},{"node":"./node_modules/balanced-match","forest":[]},{"node":"./node_modules/binary-extensions","forest":[]},{"node":"./node_modules/brace-expansion","forest":[]},{"node":"./node_modules/braces","forest":[]},{"node":"./node_modules/browser-stdout","forest":[]},{"node":"./node_modules/camelcase","forest":[]},{"node":"./node_modules/chai","forest":[]},{"node":"./node_modules/chalk","forest":[]},{"node":"./node_modules/check-error","forest":[]},{"node":"./node_modules/chokidar","forest":[]},{"node":"./node_modules/cliui","forest":[]},{"node":"./node_modules/color-convert","forest":[]},{"node":"./node_modules/color-name","forest":[]},{"node":"./node_modules/concat-map","forest":[]},{"node":"./node_modules/daggy","forest":[]},{"node":"./node_modules/debug","forest":[]},{"node":"./node_modules/decamelize","forest":[]},{"node":"./node_modules/deep-eql","forest":[]},{"node":"./node_modules/define-properties","forest":[]},{"node":"./node_modules/diff","forest":[]},{"node":"./node_modules/emoji-regex","forest":[]},{"node":"./node_modules/es-abstract","forest":[]},{"node":"./node_modules/es-array-method-boxes-properly","forest":[]},{"node":"./node_modules/es-get-iterator","forest":[]},{"node":"./node_modules/es-to-primitive","forest":[]},{"node":"./node_modules/escape-string-regexp","forest":[]},{"node":"./node_modules/esprima","forest":[]},{"node":"./node_modules/fantasy-combinators","forest":[]},{"node":"./node_modules/fantasy-land","forest":[]},{"node":"./node_modules/fantasy-laws","forest":[]},{"node":"./node_modules/fill-range","forest":[]},{"node":"./node_modules/find-up","forest":[]},{"node":"./node_modules/flat","forest":[]},{"node":"./node_modules/fs.realpath","forest":[]},{"node":"./node_modules/fsevents","forest":[]},{"node":"./node_modules/function-bind","forest":[]},{"node":"./node_modules/get-caller-file","forest":[]},{"node":"./node_modules/get-func-name","forest":[]},{"node":"./node_modules/glob","forest":[]},{"node":"./node_modules/glob-parent","forest":[]},{"node":"./node_modules/growl","forest":[]},{"node":"./node_modules/has","forest":[]},{"node":"./node_modules/has-flag","forest":[]},{"node":"./node_modules/has-symbols","forest":[]},{"node":"./node_modules/he","forest":[]},{"node":"./node_modules/inflight","forest":[]},{"node":"./node_modules/inherits","forest":[]},{"node":"./node_modules/is-arguments","forest":[]},{"node":"./node_modules/is-binary-path","forest":[]},{"node":"./node_modules/is-buffer","forest":[]},{"node":"./node_modules/is-callable","forest":[]},{"node":"./node_modules/is-date-object","forest":[]},{"node":"./node_modules/is-extglob","forest":[]},{"node":"./node_modules/is-fullwidth-code-point","forest":[]},{"node":"./node_modules/is-glob","forest":[]},{"node":"./node_modules/is-map","forest":[]},{"node":"./node_modules/is-number","forest":[]},{"node":"./node_modules/is-plain-obj","forest":[]},{"node":"./node_modules/is-regex","forest":[]},{"node":"./node_modules/is-set","forest":[]},{"node":"./node_modules/is-string","forest":[]},{"node":"./node_modules/is-symbol","forest":[]},{"node":"./node_modules/isarray","forest":[]},{"node":"./node_modules/isexe","forest":[]},{"node":"./node_modules/iterate-iterator","forest":[]},{"node":"./node_modules/iterate-value","forest":[]},{"node":"./node_modules/js-yaml","forest":[]},{"node":"./node_modules/jsverify","forest":[]},{"node":"./node_modules/lazy-seq","forest":[]},{"node":"./node_modules/locate-path","forest":[]},{"node":"./node_modules/log-symbols","forest":[]},{"node":"./node_modules/minimatch","forest":[]},{"node":"./node_modules/mocha","forest":[]},{"node":"./node_modules/ms","forest":[]},{"node":"./node_modules/normalize-path","forest":[]},{"node":"./node_modules/object-inspect","forest":[]},{"node":"./node_modules/object-keys","forest":[]},{"node":"./node_modules/object.assign","forest":[]},{"node":"./node_modules/once","forest":[]},{"node":"./node_modules/p-limit","forest":[]},{"node":"./node_modules/p-locate","forest":[]},{"node":"./node_modules/p-try","forest":[]},{"node":"./node_modules/path-exists","forest":[]},{"node":"./node_modules/path-is-absolute","forest":[]},{"node":"./node_modules/pathval","forest":[]},{"node":"./node_modules/picomatch","forest":[]},{"node":"./node_modules/promise.allsettled","forest":[]},{"node":"./node_modules/ramda","forest":[]},{"node":"./node_modules/randombytes","forest":[]},{"node":"./node_modules/rc4","forest":[]},{"node":"./node_modules/readdirp","forest":[]},{"node":"./node_modules/require-directory","forest":[]},{"node":"./node_modules/require-main-filename","forest":[]},{"node":"./node_modules/safe-buffer","forest":[]},{"node":"./node_modules/sanctuary","forest":[]},{"node":"./node_modules/sanctuary-def","forest":[]},{"node":"./node_modules/sanctuary-either","forest":[]},{"node":"./node_modules/sanctuary-maybe","forest":[]},{"node":"./node_modules/sanctuary-pair","forest":[]},{"node":"./node_modules/sanctuary-show","forest":[]},{"node":"./node_modules/sanctuary-type-classes","forest":[]},{"node":"./node_modules/sanctuary-type-identifiers","forest":[]},{"node":"./node_modules/serialize-javascript","forest":[]},{"node":"./node_modules/set-blocking","forest":[]},{"node":"./node_modules/sprintf-js","forest":[]},{"node":"./node_modules/string-width","forest":[]},{"node":"./node_modules/string.prototype.trimend","forest":[]},{"node":"./node_modules/string.prototype.trimstart","forest":[]},{"node":"./node_modules/strip-ansi","forest":[]},{"node":"./node_modules/strip-json-comments","forest":[]},{"node":"./node_modules/supports-color","forest":[]},{"node":"./node_modules/to-regex-range","forest":[]},{"node":"./node_modules/trampa","forest":[]},{"node":"./node_modules/type-detect","forest":[]},{"node":"./node_modules/typify-parser","forest":[]},{"node":"./node_modules/which","forest":[]},{"node":"./node_modules/which-module","forest":[]},{"node":"./node_modules/wide-align","forest":[]},{"node":"./node_modules/workerpool","forest":[]},{"node":"./node_modules/wrap-ansi","forest":[]},{"node":"./node_modules/wrappy","forest":[]},{"node":"./node_modules/y18n","forest":[]},{"node":"./node_modules/yargs","forest":[]},{"node":"./node_modules/yargs-parser","forest":[]},{"node":"./node_modules/yargs-unparser","forest":[]}]}
